### PR TITLE
Update providers.json

### PR DESCRIPTION
**Pull request by Jackelele**
Updated providers.json - Added Server.pro as built-in support. 

I have added some screenshots to the description too to give an overview.

### CODE REVIEW

**Comment by Camotoy** [comment]
Unrelated to the PR itself - is Floodgate defaulted to yes?

**Comment by Jackelele** [comment]
Floodgate has been defaulted to no, I can see about getting this changed if recommended better.

**Comment by Konicai** [comment]
Can the existing entry in the "support" category be merged or deleted?

**Comment by Camotoy** [comment]
That would be my recommendation. In the future we want Geyser merged into Floodgate anyway, as most people who don't know about Floodgate ask why they need a Java account to access their server.

**Comment by Jackelele** [comment]
> Can the existing entry in the "support" category be merged or deleted?

This can be merged - would you guys prefer if added under our built-in support?

**Comment by Camotoy** [comment]
Yeah - Built-In Support just means that the provider has the option for built-in support, but can have the option for manual installation. See the MCProHosting entry as an example.

**Comment by Jackelele** [comment]
Okay, I've removed it from under "support" and merged it under "In-built". I have also forwarded about enabling Floodgate by default to our team.

**Review by Camotoy — APPROVED** [review]

**Pull request merged**
